Desafio/config/routes.rb
Rails.application.routes.draw do
  resources :mercadorias
    resources :compras
    resources :vendas

  root :to => "login#index"

  get "/login" => "login#index"
  post "/login" => "login#create"
  delete "/login" => "login#destroy"

  get "/comprar" => "comprar#index"
  post "/comprar" => "comprar#create"

  get "/vender" => "vender#index"
  post "/vender" => "vender#create"

  post "/item" => "vender#create"

end

Desafio/app/models/mercadoria.rb
class Mercadoria < ActiveRecord::Base
	
	def to_s
		nome
	end
end

Desafio/app/controllers/mercadorias_controller.rb
class MercadoriasController < ApplicationController
  before_action :set_mercadoria, only: [:show, :edit, :update, :destroy]

  # GET /mercadorias
  # GET /mercadorias.json
  def index
    @mercadorias = Mercadoria.all
  end

  # GET /mercadorias/1
  # GET /mercadorias/1.json
  def show
  end

  # GET /mercadorias/new
  def new
    @mercadoria = Mercadoria.new
  end

  # GET /mercadorias/1/edit
  def edit
  end

  # POST /mercadorias
  # POST /mercadorias.json
  def create
    @mercadoria = Mercadoria.new(mercadoria_params)
    @mercadoria.quantidade = 0
    if @mercadoria.save
      redirect_to mercadorias_path, success: 'Mercadoria cadastrada com sucesso.'
    else
      render :new
    end
  end

  # PATCH/PUT /mercadorias/1
  # PATCH/PUT /mercadorias/1.json
  def update
    respond_to do |format|
      if @mercadoria.update(mercadoria_params)
        format.html { redirect_to mercadorias_path, success: 'Mercadoria was successfully updated.' }
        format.json { render :show, status: :ok, location: @mercadoria }
      else
        format.html { render :edit }
        format.json { render json: @mercadoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mercadorias/1
  # DELETE /mercadorias/1.json
  def destroy
    @mercadoria.destroy
    respond_to do |format|
      format.html { redirect_to mercadorias_url, notice: 'Mercadoria was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mercadoria
      @mercadoria = Mercadoria.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mercadoria_params
      params.require(:mercadoria).permit(:tipo, :nome, :quantidade, :preco)
    end
end

Desafio/app/helpers/mercadorias_helper.rb
module MercadoriasHelper
end

Desafio/app/views/mercadorias/_form.html.erb
<%= form_for(@mercadoria) do |f| %>

   <div class="form-group">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, :class => "form-control", :placeholder => "Informe o nome do mercadoria"  %>
  </div>

    <div class="form-group">
    <%= f.label :tipo %><br>
    <%= f.select(:tipo, 
    ["Produtos de limpeza", 
      "Lacticínios",
      "Carnes", 
      "Outro"], 
      {:selected=> "Produtos de limpeza", :include_blank => false},
      {  class: 'form-control select2'} ) %>


  </div>

                <div class="form-group">
    <%= f.label :preco %><br>
    <%= f.text_field :preco, :class => "form-control", :placeholder => "Informe o preço do mercadoria" %>
  </div>
   <div class="box-footer">
    <%= f.submit (@mercadoria.persisted? ? "Editar mercadoria" : "Cadastrar mercadoria"),:class => "btn btn-primary" %>
  </div>
<% end %>

Desafio/app/views/mercadorias/edit.html.erb
<section class="content-header">
	<h2>Edição da mercadoria <b><%= @mercadoria.nome %></b></h2>
</section>
<section class="content">

<%= render 'layouts/callbacks' %>
<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Preencha todas as informações</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
                  <div class="box-body">

    <%= render 'form' %>

</div>
</div>
</section>
<%= link_to 'Show', @mercadoria %> |
<%= link_to 'Back', mercadorias_path %>

Desafio/app/views/mercadorias/index.html.erb
<section class="content-header">
  <h2>Listando todas as mercadorias</h2>
</section>

<section class="content">

<%= render "layouts/callbacks" %>
<div class="col-xs-12">
          <% if Mercadoria.all.empty? %>
              <div class="alert alert-warning alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-warning"></i> Atenção!</h4>
                Não há nenhuma mercadoria cadastrada
              </div>  


          <% else %>
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Mercadorias</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">

              <table class="table table-hover table-linkable ">
                <tbody>
                <tr>
                  <th>Código</th>
                  <th>Nome</th>
                  <th>Tipo</th>
                  <th>Quantidade</th>
                  <th>Preço</th>
                </tr>
                <% Mercadoria.all.each do |mercadoria| %>
                  <tr data-href="<%= mercadoria_path(mercadoria) %>">
                    <td><%= mercadoria.id %></td>
                    <td><%= mercadoria.nome %></td>
                    <td><%= mercadoria.tipo %></td>
                    <td><span class="label label-success"><%= mercadoria.quantidade %> unidades</span></td>
                    <td>R$<%= mercadoria.preco %></td>
                  </tr>
                <% end %>
              </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <% end %>
                        <%= link_to new_mercadoria_path do %>
              <button class="btn btn-primary">Cadastrar nova mercadoria</button>
              <% end %>
          <!-- /.box -->
        </div>
</section>

Desafio/app/views/mercadorias/new.html.erb
<section class="content-header">
	<h2>Cadastro de nova mercadoria</h2>
</section>

<section class="content">
<%= render 'layouts/callbacks' %>
<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Preencha todas as informações</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
                  <div class="box-body">

    <%= render 'form' %>

</div>
  </div>

</section>

Desafio/app/views/mercadorias/show.html.erb
<section class="content-header"></section>

<section class="content">
<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Detalhes da mercadoria <b><%= @mercadoria.nome %></b></h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
                  <div class="box-body">
<%= render 'layouts/callbacks' %>

          <div class="table-responsive">
            <table class="table">
              <tbody><tr>
                <th style="width:50%">Nome:</th>
                <td><%= @mercadoria.nome %></td>
              </tr>
              <tr>
                <th>Tipo</th>
                <td><%= @mercadoria.tipo %></td>
              </tr>
              <tr>
                <th>Quantidade</th>
                <td><%= @mercadoria.quantidade %> unidades</td>
              </tr>
              <tr>
                <th>Preço</th>
                <td>R$<%= @mercadoria.preco %></td>
              </tr>
            </tbody></table>
          </div>
  </div>

  <div class="box-footer">
<%= link_to edit_mercadoria_path(@mercadoria) do %>
<button class="btn btn-primary">Editar mercadoria</button>
<% end %> 

  </div>
</div>

</section>