Desafio/config/routes.rb
Rails.application.routes.draw do
  resources :mercadorias
    resources :compras
    resources :vendas

  root :to => "login#index"

  get "/login" => "login#index"
  post "/login" => "login#create"
  delete "/login" => "login#destroy"

  get "/comprar" => "comprar#index"
  post "/comprar" => "comprar#create"

  get "/vender" => "vender#index"
  post "/vender" => "vender#create"

  post "/item" => "vender#create"

end

Desafio/app/models/venda.rb
class Venda < ActiveRecord::Base
	belongs_to :mercadoria
	belongs_to :vendedor

	def have_mercadoria_in_estoque?
		mercadoria.quantidade >= quantidade
	end
end

Desafio/app/controllers/vendas_controller.rb
class VendasController < ApplicationController
  before_action :set_venda, only: [:show, :edit, :update, :destroy]

  # GET /vendas
  # GET /vendas.json
  def index
    @vendas = Venda.all
  end

  # GET /vendas/1
  # GET /vendas/1.json
  def show
  end

  # GET /vendas/new
  def new
    @mercadorias = Mercadoria.all
    @venda = Venda.new  
  end

  # GET /vendas/1/edit
  def edit
  end

  # POST /vendas
  # POST /vendas.json
  def create
    @venda = Venda.new(venda_params)
    @mercadoria = @venda.mercadoria
    if @venda.have_mercadoria_in_estoque?
      @mercadoria.quantidade -= @venda.quantidade
      current_user.saldo += @venda.preco
      if @venda.save && @mercadoria.save && current_user.save
        redirect_to mercadorias_path, 
          success: "#{@venda.quantidade} #{@mercadoria.nome} vendidos com sucesso."
      else
        redirect_to new_venda_path, :error => ["Erro ao cadastrar venda."]
      end
    else
        redirect_to new_venda_path, :error => ["Você não possui tanto deste produto em estoque."]

    end
  end



  # DELETE /vendas/1
  # DELETE /vendas/1.json
  def destroy
    @venda.destroy
    respond_to do |format|
      format.html { redirect_to vendas_url, notice: 'Venda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venda
      @venda = Venda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venda_params
      params.require(:venda).permit!
    end
end

Desafio/app/helpers/vendas_helper.rb
module VendasHelper
end

Desafio/app/views/vendas/_form.html.erb
<%= form_for(@venda) do |f| %>

    <div class="form-group">
    <label>Selecione o produto que deseja vender</label>
    <%= f.select(:mercadoria_id, @mercadorias.map { |l| ["#{l.nome} (#{l.quantidade} unidades) ", l.id] }, 
      {:include_blank => false},
      {  class: 'form-control select2'} ) %>


  </div>
                <div class="form-group">
    <%= f.label :quantidade %><br>
    <%= f.number_field :quantidade, :class => "form-control", :placeholder => "Informe a quantidade do mercadoria" %>
  </div>
                <div class="form-group">
    <%= f.label :preco %><br>
    <%= f.text_field :preco, :class => "form-control", :placeholder => "Informe o preço do mercadoria" %>
  </div>
    <%= f.submit "Vender mercadoria", :class => "btn btn-primary" %>

  </div>
<% end %>

Desafio/app/views/vendas/edit.html.erb
<h1>Editing Venda</h1>

<%= render 'form' %>

<%= link_to 'Show', @venda %> |
<%= link_to 'Back', vendas_path %>

Desafio/app/views/vendas/index.html.erb
<section class="content-header">
  <h2>Listando todas as vendas realizadas</h2>
</section>

<section class="content">

<%= render "layouts/callbacks" %>
<div class="col-xs-12">
          <% if @vendas.empty? %>
              <div class="alert alert-warning alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-warning"></i> Atenção!</h4>
                Ainda não foi feita nenhuma venda!
              </div>  


          <% else %>
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Vendas</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">

              <table class="table table-hover table-linkable ">
                <tbody><tr>
                  <th>Código</th>


                  <th>Nome da mercadoria</th>
                  <th>Quantidade vendida</th>
                  <th>Preço do produto venda</th>
                  <th>Preço total da venda</th>
                </tr>
                <% @vendas.each do |venda| %>
                  <tr data-href="<%= venda_path(venda) %>">
                    <td><%= venda.id %></td>
                    <td><%= venda.mercadoria.nome %></td>
                    <td><%= venda.quantidade %></td>
                    <td>R$<%= venda.mercadoria.preco %></td>
                    <td>R$<%= venda.preco %></td>
                  </tr>
                <% end %>
              </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <% end %>
                        <%= link_to new_venda_path do %>
              <button class="btn btn-primary">Fazer uma nova venda</button>
              <% end %>
          <!-- /.box -->
        </div>
</section>

Desafio/app/views/vendas/new.html.erb
<script>
var mercadorias = [];

<% @mercadorias.each do |mercadoria| %>
mercadorias.push({"id" : <%= mercadoria.id %>, "preco" : <%= mercadoria.preco %>});
<% end %>
</script>

<section class="content-header">
  <h2>Venda de mercadoria</h2>
</section>

<section class="content">
<%= render 'layouts/callbacks' %>
<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Preencha todas as informações</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
                  <div class="box-body">

    <%= render 'form' %>

</div>
  </div>

</section>

Desafio/app/views/vendas/show.html.erb
<section class="content-header"></section>

<section class="content">
<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Detalhes da venda <b>#<%= @venda.id %></b></h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
                  <div class="box-body">
<%= render 'layouts/callbacks' %>

          <div class="table-responsive">
            <table class="table">
              <tbody><tr>
                <th style="width:50%">Nome da mercadoria vendida:</th>
                <td><%= @venda.mercadoria.nome %></td>
              </tr>
              <tr>
                <th>Quantidade vendida</th>
                <td><%= @venda.quantidade %></td>
              </tr>
              <tr>
                <th>Preço total da venda</th>
                <td>R$<%= @venda.preco %></td>
              </tr>

            </tbody></table>
          </div>
  </div>

  <div class="box-footer">
<%= link_to vendas_path do %>
<button class="btn btn-primary">Voltar</button>
<% end %> 

  </div>
</div>

</section>