Desafio/config/routes.rb
Rails.application.routes.draw do
  resources :mercadorias
    resources :compras
    resources :vendas

  root :to => "login#index"

  get "/login" => "login#index"
  post "/login" => "login#create"
  delete "/login" => "login#destroy"

  get "/comprar" => "comprar#index"
  post "/comprar" => "comprar#create"

  get "/vender" => "vender#index"
  post "/vender" => "vender#create"

  post "/item" => "vender#create"

end

Desafio/app/views/layouts/_callbacks.html.erb
<% if error %>
<div class="summary-errors alert alert-danger alert-dismissible">
	<button type="button" class="close" aria-label="Close" data-dismiss="alert">
		<span aria-hidden="true">×</span>
	</button>
		<h4><i class="icon fa fa-ban"></i> Erro!</h4> 
	<p>    <ul>

      <% error.each do |field, msg|  %>
      	<% msg ||= field %>
        <li><%= msg.to_s %></li>
      <% end %>


      </ul></p>
</div>
<% end %>

<% if success %>
<div class="summary-errors alert alert-success alert-dismissible">
	<button type="button" class="close" aria-label="Close" data-dismiss="alert">
		<span aria-hidden="true">×</span>
	</button>
	<h4><i class="icon fa fa-check"></i> Sucesso!</h4>
	<p><ul><li><%= success %></li></ul></p>
</div>
<% end %>

Desafio/app/views/layouts/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <%= link_to mercadorias_path, :class => "logo" do %> 
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini">Desafio ValeMOBI</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg">Desafio ValeMOBI
    </span>
    <% end %>
  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
      <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
        <%= image_tag "avatar", :class => "user-image" %>
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs"><%= current_user.nome %></span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                      <%= image_tag "avatar", :class => "img-circle" %>


                <p>
                  <%= current_user.nome %>
                  <small>Vendedor</small>

                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-12 text-center">
                      <%= Mercadoria.all.size %>
                     mercadorias cadastradas 
                  </div>

                </div>
                  
                  
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">

                <div class="pull-right">
                 <%= link_to login_path, method: :delete do %>
                  <button class="btn btn-default btn-flat">Deslogar</button>
                  <% end %>
                </div>
              </li>
            </ul>
          </li>
        <li>
        </li>
      </ul>
    </div>
  </nav>
</header>

Desafio/app/views/layouts/_sidebar.html.erb
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->

      <div class="user-panel">

        <%= link_to mercadorias_path, :class => "pull-left image" do %>
        <%= image_tag "avatar", :class => "img-circle" %>
        <% end %>


        <%= link_to mercadorias_path, :class => "pull-left info" do %>

        <p><%= current_user.nome %></p>


        <!-- Status -->
        <p>Saldo: R$ <%= current_user.saldo %></p>
        <% end %>

      </div>

      <!-- 
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      search form -->

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">
        <li class="header">Painel principal</li>
        <!-- Optionally, you can add icons to the links -->
        <li>
          <%= link_to mercadorias_path do %>
            <i class="fa fa-search"></i> <span>Ver mercadorias</span> 
          <% end %>
        </li>
        <li>
          <%= link_to new_compra_path do %>
            <i class="glyphicon glyphicon-briefcase"></i> <span>Comprar mercadoria</span> 
          <% end %>
        </li>
        <li>
          <%= link_to compras_path do %>
            <i class="fa fa-search"></i> <span>Ver compras realizadas</span> 
          <% end %>
        </li>

        <li>
          <%= link_to new_venda_path do %>
            <i class="glyphicon glyphicon-usd"></i> <span>Vender mercadorias</span> 
          <% end %>
        </li>
        <li>
          <%= link_to vendas_path do %>
            <i class="fa fa-search"></i> <span>Ver vendas realizadas</span> 
          <% end %>
        </li>
        <!--        <li><a href="#"><i class="fa fa-link"></i> <span>Another Link</span></a></li> -->

      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

        <div class="control-sidebar-bg"></div>

Desafio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio ValeMOBI - Brendow Paolillo</title>

    <%= csrf_meta_tags %>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  params[:controller] , media: 'all', 'data-turbolinks-track': 'reload' %>


      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

  </head>


  <body class='hold-transition skin-blue sidebar-mini'>
	<% if current_user %>
<div class='wrapper'>
  		<%= render 'layouts/header' %>


  		<%= render 'layouts/sidebar' %>

	    <div class="content-wrapper">
		    <%= yield %>
		</div>

     <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Desenvolvido por Brendow Paolillo
    </div>
    <!-- Default to the left -->
    <strong>Desenvolvido para o Desafio da ValeMOBI</strong>
  </footer>

  <!-- Control Sidebar -->

  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
  </div>
	<% else %>

		<%= yield %>

	<% end %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCrL-gWhIqMfMg0cElTm0IpidOEWA38Qa4"></script>	

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag params[:controller] %>


  </body>
</html>