Desafio/config/routes.rb
Rails.application.routes.draw do
  resources :mercadorias
    resources :compras
    resources :vendas

  root :to => "login#index"

  get "/login" => "login#index"
  post "/login" => "login#create"
  delete "/login" => "login#destroy"

  get "/comprar" => "comprar#index"
  post "/comprar" => "comprar#create"

  get "/vender" => "vender#index"
  post "/vender" => "vender#create"

  post "/item" => "vender#create"

end

Desafio/app/models/compra.rb
class Compra < ActiveRecord::Base
	belongs_to :mercadoria
	belongs_to :vendedor
end

Desafio/app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  before_action :set_compra, only: [:show, :edit, :update, :destroy]

  # GET /compras
  # GET /compras.json
  def index
    @compras = Compra.all
  end

  # GET /compras/1
  # GET /compras/1.json
  def show
  end

  # GET /compras/new
  def new
    @compra = Compra.new
    @mercadorias = Mercadoria.all
    @item_compra = ItemCompra.new
  end

  # GET /compras/1/edit
  def edit
  end

  # POST /compras
  # POST /compras.json
  def create
    @compra = Compra.new(compra_params)
    @mercadoria = @compra.mercadoria
    @mercadoria.quantidade += @compra.quantidade
    if current_user.saldo >= @compra.preco
      current_user.saldo -= @compra.preco
      if @compra.save && @mercadoria.save && current_user.save
        redirect_to mercadorias_path, 
          success: ["#{@compra.quantidade} #{@mercadoria.nome} comprados com sucesso."]
      else
        render :new
      end
    else
   redirect_to new_compra_path, 
          error: ["Você não tem saldo suficiente."]
    end
  end

  # PATCH/PUT /compras/1
  # PATCH/PUT /compras/1.json
  def update
    respond_to do |format|
      if @compra.update(compra_params)
        format.html { redirect_to @compra, notice: 'Compra was successfully updated.' }
        format.json { render :show, status: :ok, location: @compra }
      else
        format.html { render :edit }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compras/1
  # DELETE /compras/1.json
  def destroy
    @compra.destroy
    respond_to do |format|
      format.html { redirect_to compras_url, notice: 'Compra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra
      @compra = Compra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compra_params
      params.require(:compra).permit!
    end
end

Desafio/app/helpers/compras_helper.rb
module ComprasHelper
end

Desafio/app/views/compras/_form.html.erb
<%= form_for(@compra) do |f| %>

    <div class="form-group">
    <label>Selecione o produto que deseja comprar</label>
    <%= f.select(:mercadoria_id, @mercadorias.map { |l| ["#{l.nome} (R$ #{l.preco})", l.id] }, 
      {:include_blank => false},
      {  class: 'form-control select2'}) %>


  </div>
                <div class="form-group">
    <%= f.label :quantidade %><br>
    <%= f.number_field :quantidade, :class => "form-control", :placeholder => "Informe a quantidade do mercadoria", :min => 1 %>
  </div>
                <div class="form-group">
    <%= f.label :preco %><br>
    <%= f.text_field :preco, :class => "form-control", :placeholder => "Informe o preço do mercadoria" %>
  </div>
    <%= f.submit "Comprar mercadoria", :class => "btn btn-primary" %>

  </div>
<% end %>

Desafio/app/views/compras/edit.html.erb
<h1>Editing Compra</h1>

<%= render 'form' %>

<%= link_to 'Show', @compra %> |
<%= link_to 'Back', compras_path %>

Desafio/app/views/compras/index.html.erb
<section class="content-header">
  <h2>Listando todas as compras realizadas</h2>
</section>

<section class="content">

<%= render "layouts/callbacks" %>
<div class="col-xs-12">
          <% if @compras.empty? %>
              <div class="alert alert-warning alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-warning"></i> Atenção!</h4>
                Ainda não foi feita nenhuma compra!
              </div>  


          <% else %>
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Compras</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">

              <table class="table table-hover table-linkable ">
                <tbody><tr>
                  <th>Código</th>


                  <th>Nome da mercadoria</th>
                  <th>Quantidade comprada</th>
                  <th>Preço do produto compra</th>
                  <th>Preço total da compra</th>
                </tr>
                <% @compras.each do |compra| %>
                  <tr data-href="<%= compra_path(compra) %>">
                    <td><%= compra.id %></td>
                    <td><%= compra.mercadoria.nome %></td>
                    <td><%= compra.quantidade %></td>
                    <td>R$<%= compra.mercadoria.preco %></td>
                    <td>R$<%= compra.preco %></td>
                  </tr>
                <% end %>
              </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <% end %>
                        <%= link_to new_compra_path do %>
              <button class="btn btn-primary">Fazer uma nova compra</button>
              <% end %>
          <!-- /.box -->
        </div>
</section>

Desafio/app/views/compras/new.html.erb
<script>
var mercadorias = [];

<% @mercadorias.each do |mercadoria| %>
mercadorias.push({"id" : <%= mercadoria.id %>, "preco" : <%= mercadoria.preco %>});
<% end %>
</script>

<section class="content-header">
  <h2>Compra de mercadoria (adição no estoque)</h2>
</section>

<section class="content">
<%= render 'layouts/callbacks' %>
<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Preencha todas as informações</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
                  <div class="box-body">

    <%= render 'form' %>

</div>
  </div>

</section>

Desafio/app/views/compras/show.html.erb
<section class="content-header"></section>

<section class="content">
<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Detalhes da compra <b>#<%= @compra.id %></b></h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
                  <div class="box-body">
<%= render 'layouts/callbacks' %>

          <div class="table-responsive">
            <table class="table">
              <tbody><tr>
                <th style="width:50%">Nome da mercadoria comprada:</th>
                <td><%= @compra.mercadoria.nome %></td>
              </tr>
              <tr>
                <th>Quantidade vendida</th>
                <td><%= @compra.quantidade %></td>
              </tr>
              <tr>
                <th>Preço total da compra</th>
                <td>R$<%= @compra.preco %></td>
              </tr>

            </tbody></table>
          </div>
  </div>

  <div class="box-footer">
<%= link_to compras_path do %>
<button class="btn btn-primary">Voltar</button>
<% end %> 

  </div>
</div>

</section>